Repository shipwright-io/website, pull requests merged in 2021-03, with the labels that each got.

#26 Fix some typos
  README.md
  content/en/_index.html
Labels: approved, kind/cleanup, lgtm

#25 Update docs link to main README.md
  content/en/docs/_index.md
Labels: approved, lgtm

#28 Add Favicons
  layouts/partials/favicons.html
  static/favicons/apple-touch-icon-180x180.png
  static/favicons/browserconfig.xml
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
  static/favicons/pwa-192x192.png
  static/favicons/pwa-512x512.png
  static/favicons/tile150x150.png
  static/favicons/tile310x150.png
  static/favicons/tile310x310.png
  static/favicons/tile70x70.png
Labels: approved, lgtm

#27 Import documentation
  content/en/contact/_index.md
  content/en/docs/_index.md
  content/en/docs/api/build.md
  content/en/docs/api/buildrun.md
  content/en/docs/api/buildstrategies.md
  content/en/docs/authentication.md
  content/en/docs/configuration.md
  content/en/docs/metrics.md
  content/en/docs/profiling.md
Labels: approved, kind/documentation, lgtm
