Repository shipwright-io/website, pull requests merged in 2024-07, with the labels that each got.

#122 v0.13.0: Add Operator Instructions
  content/en/blog/posts/2024-03-27-build-release-v0.13.0.md
Labels: lgtm, approved, kind/documentation

#123 Add blog for vulnerability scanning in shipwright
  content/en/blog/posts/2024-07-15-vulnerability-scanning.md
Labels: lgtm, approved, size/L

#124 Fix some markdown formatting for Vulscan blog
  content/en/blog/posts/2024-07-15-vulnerability-scanning.md
Labels: lgtm, approved, size/S
