Repository shipwright-io/website, pull requests merged in 2025-03, with the labels that each got.

#153 Sync documentation updates from build v0.15.2
  content/en/docs/build/build.md
  content/en/docs/build/buildrun.md
  content/en/docs/build/buildstrategies.md
  content/en/docs/build/configuration.md
  content/en/docs/build/metrics.md
  content/en/docs/getting-started/installation.md
Labels: lgtm, approved, size/M, kind/documentation

#152 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#150 feat: Announce v0.15.z Releases
  content/en/blog/posts/2025-02-28-release-v0.15.md
Labels: lgtm, approved, kind/documentation, size/L

#147 feat: Generate Build API docs
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  api-gen/build.yaml
  api-gen/templates/markdown/gv_details.tpl
  api-gen/templates/markdown/gv_list.tpl
  api-gen/templates/markdown/type.tpl
  api-gen/templates/markdown/type_members.tpl
  content/en/docs/ref/_index.md
  content/en/docs/ref/api/_index.md
  content/en/docs/ref/api/build.md
  hack/gen-api-docs.sh
Labels: kind/feature, lgtm, approved, size/XXL

#151 fix: Improve Main Image
  content/en/_index.html
  content/en/featured-background.jpg
  content/en/featured-background.png
Labels: kind/feature, lgtm, approved, size/S

#154 Update main page links to point to v0.15
  content/en/_index.html
Labels: lgtm, approved, kind/documentation, size/XS

#156 fix: Correct Link for Feedback
  hugo.yaml
Labels: kind/bug, lgtm, approved, size/XS
